### ISSUE TITLE
<공지> 연구실 Core-Time에는 PS 자제하세요

### ISSUE THREAD

**Issue by dkdlelk99** [dkdlelk99/CSOS-Algorithm#101]
@ghwns82 

![image](https://user-images.githubusercontent.com/49552766/130589318-676b00d7-513f-44e8-ad1f-9384099f2a3f.png)

![image](https://user-images.githubusercontent.com/49552766/130589190-36255017-6b15-4c6c-adc5-db9b0600ec49.png)

![image](https://user-images.githubusercontent.com/49552766/130589083-7bb8a99e-5364-4f2e-ace9-35e40f7e14ce.png)

# 그 시간에 PS하라고 컴퓨터 주고 자리에 앉혀둔거 아닙니다. <br>본업에 충실하세요. 보기 좋지 않습니다.

**Comment by ghwns82** [comment]
확인했습니다
