### ISSUE TITLE
희아 보시오

### ISSUE THREAD

**Issue by dkdlelk99** [dkdlelk99/CSOS-Algorithm#3]
@KIMLEENA 

md 파일에 (너무) 이쁘게 정리 잘했습니다. 
그런데 md 파일에 소스 코드까지 들어가면 내가 올린 PR처럼 코드 리뷰를 하기가 어려우니 내일은 오늘 알려준 방법으로 PR을 한 번 날려보는 것을 추천함
내가 올린 PR도 한 번 보는 것을 추천

**Comment by KIMLEENA** [comment]
내일은 오늘 알려준 방법...... 어디가셨나요....... 돌아오세요.....

**Comment by dkdlelk99** [comment]
> 내일은 오늘 알려준 방법...... 어디가셨나요....... 돌아오세요.....

아 질문인가요?? 좋아요 내일 갑니다 :D 
질문은 언제나 환영이에요. 오히려 장려해야한다고 생각합니다.

근데 `Fork`랑 `PR` 개념 설명해줬을때 분명히 알겠다는 반응 했으면서...
